version: 1
default_profile: default
palette:
  amber: "#ca9102"
  address: "#d787ff"
  blue: "#0099ff"
  blue_gray: "#87afaf"
  bright_red: "#ff3333"
  cyan: "#65d7fd"
  danger: "#ff5f5f"
  dark_red: "#c71800"
  gold: "#cab902"
  green: "#00ff00"
  info: "#5fafff"
  interface: "#5fffff"
  interface_blue: "#0099ff"
  light_blue: "#5fafff"
  lime: "#28c501"
  mint: "#03d28d"
  number: "#d7d787"
  orange: "#ffaf00"
  red: "#ff0000"
  steel_blue: "#5698c8"
  success: "#5fd75f"
  warning: "#ffd75f"
  yellow: "#ffff00"
  yellow_green: "#79bf02"
